scss_files: "**/*.scss"
linters:
  SelectorFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_BEM
  NestingDepth:
    enabled: true
    max_depth: 3
    severity: warning
